[[ldap.repositories.queries]]
= Query Methods

Most of the data access operations you usually trigger on a repository result in a query being run against the LDAP directory.
Defining such a query is a matter of declaring a method on the repository interface, as the following example shows:

.PersonRepository with query methods
[source,java]
----
interface PersonRepository extends PagingAndSortingRepository<Person, String> {

    List<Person> findByLastname(String lastname);                            <1>

    List<Person> findByLastnameFirstname(String lastname, String firstname); <2>
}
----

<1> The method shows a query for all people with the given `lastname`.
The query is derived by parsing the method name for constraints that can be concatenated with `And` and `Or`.
Thus, the method name results in a query expression of `(&(objectclass=person)(lastname=lastname))`.
<2> The method shows a query for all people with the given `lastname` and `firstname`.
The query is derived by parsing the method name.
Thus, the method name results in a query expression of `(&(objectclass=person)(lastname=lastname)(firstname=firstname))`.

The following table provides samples of the keywords that you can use with query methods:

[cols="1,2,3",options="header"]
.Supported keywords for query methods
|===
| Keyword
| Sample
| Logical result

| `LessThanEqual`
| `findByAgeLessThanEqual(int age)`
| `(attribute<=age)`

| `GreaterThanEqual`
| `findByAgeGreaterThanEqual(int age)`
| `(attribute>=age)`

| `IsNotNull`, `NotNull`
| `findByFirstnameNotNull()`
| `(firstname=*)`

| `IsNull`, `Null`
| `findByFirstnameNull()`
| `(!(firstname=*))`

| `Like`
| `findByFirstnameLike(String name)`
| `(firstname=name)`

| `NotLike`, `IsNotLike`
| `findByFirstnameNotLike(String name)`
| `(!(firstname=name*))`

| `StartingWith`
| `findByStartingWith(String name)`
| `(firstname=name*)`

| `EndingWith`
| `findByFirstnameLike(String name)`
| `(firstname=*name)`

| `Containing`
| `findByFirstnameLike(String name)`
| `(firstname=\*name*)`

| `(No keyword)`
| `findByFirstname(String name)`
| `(Firstname=name)`

| `Not`
| `findByFirstnameNot(String name)`
| `(!(Firstname=name))`

|===
